# .travis.yml
language: node_js
node_js: 
  - stable
addons: 
  ssh_known_hosts: organa.webhouse.net
install:
- npm ci
cache:
  directories:
  - "$HOME/.npm"
before_deploy: 
  - "openssl aes-256-cbc -K $encrypted_9ff15c749c3b_key -iv $encrypted_9ff15c749c3b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d"
  - "eval \"$(ssh-agent -s)\""
  - "chmod 600 /tmp/deploy_rsa"
  - "ssh-add /tmp/deploy_rsa"
deploy:
  - provider: script
    script: bash deploy.sh master $TRAVIS_BUILD_DIR
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_BRANCH = master
    true: 
      branch: master
  - provider: script
    script: bash deploy.sh dev $TRAVIS_BUILD_DIR
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = dev
    true: 
      branch: dev

notifications: 
  email: true
  # slack: "webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu"
  slack: "$SLACK_KEY"
