# .travis.yml
addons: 
  ssh_known_hosts: organa.webhouse.net
install:
- npm ci
# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"
before_deploy: 
  - "openssl aes-256-cbc -K $encrypted_9ff15c749c3b_key -iv $encrypted_9ff15c749c3b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d"
  - "eval \"$(ssh-agent -s)\""
  - "chmod 600 /tmp/deploy_rsa"
  - "ssh-add /tmp/deploy_rsa"
deploy: 
  - 
    provider: script
    script: "rsync -r --quiet $TRAVIS_BUILD_DIR/ deploy@organa.webhouse.net:/srv/nodejs/senti/senti-api"
    skip_cleanup: true
    true: 
      branch: master

after_deploy:
  - "echo Now running npm install on host"
  - "ssh deploy@organa.webhouse.net 'sudo npm install --prefix /srv/nodejs/senti/senti-api'"
  - "echo Now restarting API service"
  - "ssh deploy@organa.webhouse.net 'sudo /srv/nodejs/api-restart.sh'"

language: node_js
node_js: 
  - stable
notifications: 
  email: true
  slack: "webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu"
